# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  workflow_dispatch:
  schedule:
    # UTC 16 点也就是东八区 0 点定时执行任务
    # - cron:  '0 16 * * *'
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JAVA
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - run: chmod +x ./gradlew && ./gradlew run --no-daemon

    - name: Commit files
      run: |
         git config user.email "acc8226@qq.com"
         git config user.name "Github Action"
         git pull
         git add README.md sources.txt archives/*
         git commit -m "update by Github Action"

    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
